package dat250.appassignB.model;


import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface AppUserRepository extends JpaRepository<AppUser, Integer> {
    //Spring Data JPA will generate the implementation of this repository automatically,
    //Do we need to add any other methods, than the ones generated by Spring JPA data?
}

